site_name: Sitar Simulation Framework
site_description: A cycle-based discrete-event modeling framework
site_author: Neha Karanjkar
site_dir: generated_site
use_directory_urls: false

repo_url: https://github.com/sitar-sim/sitar
repo_name: sitar-sim/sitar
theme:
  #logo: assets/sitar_logo.png
  name: material
  highlightjs: false
  
  palette: 
    # Palette toggle for light mode
    - scheme: colorful
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    #- navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
hooks:
  - docs/hooks/sitar_download.py
plugins:
  - search
extra_css:
  - stylesheets/extra.css

nav:
  - Introduction:
      - What is Sitar: index.md
      - Getting Started: getting_started.md

  - Basic Concepts:
      - Modules and Nets: 2_basic_concepts/components_modules_nets.md
      - Timing: 2_basic_concepts/timing_and_execution_model.md
      - Module Behavior: 2_basic_concepts/module_behavior.md
      - Tokens: 2_basic_concepts/io_and_tokens.md
      - Execution Model: 2_basic_concepts/execution_model.md

  - Language and Examples:
      - Describing Structure:
          - Modules and hierarchy: 3_language_and_examples/modules_and_hierarchy.md
          - Nets, ports, and connections: 3_language_and_examples/nets_and_ports.md
          - Parameters and templates: 3_language_and_examples/parameters_and_templates.md
          - Regular structures: 3_language_and_examples/regular_structures.md

      - Describing Behavior:
          - Sequences and statements: 3_language_and_examples/sequence.md
          - Code blocks: 3_language_and_examples/code_blocks.md
          - Wait: 3_language_and_examples/wait.md
          - Logging: 3_language_and_examples/logging.md
          - If-else: 3_language_and_examples/if_else.md
          - Do-while: 3_language_and_examples/do_while.md
          - Parallel blocks: 3_language_and_examples/parallel.md
          - Procedures: 3_language_and_examples/procedures.md
          - Procedures for I/O: 3_language_and_examples/io_procedures.md

  - Examples:
      - Basic Examples:
          - Shift Register: 4_examples/basic_examples/shift_register.md
          - State Machine: 4_examples/basic_examples/state_machine.md
          - Producer Consumer: 4_examples/basic_examples/producer_consumer.md
          - Router: 4_examples/basic_examples/router.md

      - Advanced Examples:
          - Processor and Memory: 4_examples/advanced_examples/processor_model.md
          - Pipelined Processor: 4_examples/advanced_examples/pipelined_processor.md
          - Mesh: 4_examples/advanced_examples/mesh.md

  - Parallel Execution:
      - Enabling Parallel Execution: 5_parallel_execution/parallel_execution.md
      - Measuring Speedup: 5_parallel_execution/speedups.md

  - How Sitar Works:
      - Translation: how_sitar_works/translation.md
      - Kernel and execution: how_sitar_works/kernel.md

  - More About Sitar:
      - References: references.md
      - Authors: authors.md
      - Development Notes: development.md

