/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g
 *     -                            On : 2015-02-05 16:22:03
 *     -                for the parser : output_templateParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "output_templateParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   poutput_templateParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  poutput_templateParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->poutput_templateParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->poutput_templateParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */

/* ruleAttributeScopeFuncDecl(scope)
 */
/* -----------------------------------------------------------------------------
 * Function declarations for creating a output_templateParser_top scope set
 */
static poutput_templateParser_top_SCOPE   poutput_templateParser_topPush(poutput_templateParser ctx);
static void ANTLR3_CDECL topFree(poutput_templateParser_top_SCOPE scope);
/* ----------------------------------------------------------------------------- */


/* ruleAttributeScopeFuncs(scope)
 */
/* attributeFuncs(scope)
 */

static void ANTLR3_CDECL topFree(poutput_templateParser_top_SCOPE scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Allocate initial memory for a output_templateParser top scope variable stack entry and
 *         add it to the top of the stack.
 *
 * \remark
 * By default the structure is freed with ANTLR_FREE(), but you can use the
 * the \@init action to install a pointer to a custom free() routine by
 * adding the code:
 * \code
 *   ctx->poutput_templateParser_topTop->free = myroutine;
 * \endcode
 *
 * With lots of comments of course! The routine should be declared in
 * \@members { } as:
 * \code
 *   void ANTLR3_CDECL myfunc( poutput_templateParser_top_SCOPE ptr).
 * \endcode
 *
 * It should perform any custom freeing stuff that you need (call ANTLR_FREE3, not free()
 * NB: It should not free the pointer it is given, which is the scope stack entry itself
 * and will be freed by the function that calls your custom free routine.
 *
 */
static poutput_templateParser_top_SCOPE
poutput_templateParser_topPush(poutput_templateParser ctx)
{
    /* Pointer used to create a new set of attributes
     */
    poutput_templateParser_top_SCOPE      newAttributes;

    /* Allocate the memory for a new structure if we need one.
     */
    if (ctx->poutput_templateParser_topStack->size(ctx->poutput_templateParser_topStack) > ctx->poutput_templateParser_topStack_limit)
    {
        // The current limit value was less than the number of scopes available on the stack so
        // we can just reuse one. Our limit tracks the stack count, so the index of the entry we want
        // is one less than that, or conveniently, the current value of limit.
        //
        newAttributes = (poutput_templateParser_top_SCOPE)ctx->poutput_templateParser_topStack->get(ctx->poutput_templateParser_topStack, ctx->poutput_templateParser_topStack_limit);
    }
    else
    {
        // Need a new allocation
        //
        newAttributes = (poutput_templateParser_top_SCOPE) ANTLR3_MALLOC(sizeof(output_templateParser_top_SCOPE));
        if  (newAttributes != NULL)
        {
            /* Standard ANTLR3 library implementation
             */
            ctx->poutput_templateParser_topStack->push(ctx->poutput_templateParser_topStack, newAttributes, (void (*)(void *))topFree);
        }
    }

    // Blank out any previous free pointer, the user might or might install a new one.
    //
    newAttributes->free = NULL;

    // Indicate the position in the available stack that the current level is at
    //
    ctx->poutput_templateParser_topStack_limit++;

	/* Return value is the pointer to the new entry, which may be used locally
	 * without de-referencing via the context.
     */
    return  newAttributes;
}







/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   output_templateParserTokenNames[11+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "AT",
        (pANTLR3_UINT8) "ESC_LBR",
        (pANTLR3_UINT8) "ESC_RBR",
        (pANTLR3_UINT8) "IDENT",
        (pANTLR3_UINT8) "LBR",
        (pANTLR3_UINT8) "LPAREN",
        (pANTLR3_UINT8) "NOT1",
        (pANTLR3_UINT8) "PLAINTEXT",
        (pANTLR3_UINT8) "RBR",
        (pANTLR3_UINT8) "RPAREN",
        (pANTLR3_UINT8) "SLASH"
       };


/* ruleAttributeScopeFuncMacro(scope)
 */
/** Function for popping the top value from a poutput_templateParser_topStack
 */
void
poutput_templateParser_topPop(poutput_templateParser ctx)
{
    // First see if the user defined a function they want to be called when a
    // scope is popped/freed.
    //
	// If the user supplied the scope entries with a free function,then call it first
	//
    if	(SCOPE_TOP(top)->free != NULL)
	{
        SCOPE_TOP(top)->free(SCOPE_TOP(top));
	}

    // Now we decrement the scope's upper limit bound. We do not actually pop the scope as
    // we want to reuse scope entries if we do continuous push and pops. Most scopes don't
    // next too far so we don't want to keep freeing and allocating them
    //
    ctx->poutput_templateParser_topStack_limit--;
    SCOPE_TOP(top) = (poutput_templateParser_top_SCOPE)(ctx->poutput_templateParser_topStack->get(ctx->poutput_templateParser_topStack, ctx->poutput_templateParser_topStack_limit - 1));
}



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	top    (poutput_templateParser ctx);
static 
 void
	statement    (poutput_templateParser ctx, bool X);
static 
 void
	conditional    (poutput_templateParser ctx, bool X);
static 
 void
	action    (poutput_templateParser ctx, bool X);
static 
 void
	attribute    (poutput_templateParser ctx, bool X);
static 
 void
	plaintext    (poutput_templateParser ctx, bool X);
static 
 void
	esc_brackets    (poutput_templateParser ctx, bool X);
static 
 output_templateParser_simple_text_return
	simple_text    (poutput_templateParser ctx, bool X);
static void	output_templateParserFree(poutput_templateParser ctx);
static void     output_templateParserReset (poutput_templateParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new output_templateParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API poutput_templateParser
output_templateParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return output_templateParserNewSSD(instream, NULL);
}

/** \brief Create a new output_templateParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API poutput_templateParser
output_templateParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    poutput_templateParser ctx;	    /* Context structure we will build and return   */

    ctx	= (poutput_templateParser) ANTLR3_CALLOC(1, sizeof(output_templateParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in output_templateParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our output_templateParser interface
     */
    ctx->top	= top;
    ctx->statement	= statement;
    ctx->conditional	= conditional;
    ctx->action	= action;
    ctx->attribute	= attribute;
    ctx->plaintext	= plaintext;
    ctx->esc_brackets	= esc_brackets;
    ctx->simple_text	= simple_text;
    ctx->free			= output_templateParserFree;
    ctx->reset			= output_templateParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
    /* ruleAttributeScope(scope)
     */
    ctx->poutput_templateParser_topPush     = poutput_templateParser_topPush;
    ctx->poutput_templateParser_topStack    = antlr3StackNew(0);
    ctx->poutput_templateParser_topStack_limit    = 0;
    ctx->poutput_templateParser_topTop      = NULL;





    	ctx->_globalData= NULL;
    	

    /* Install the token table
     */
    PSRSTATE->tokenNames   = output_templateParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
output_templateParserReset (poutput_templateParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 output_templateParserFree(poutput_templateParser ctx)
 {
    /* Free any scope memory
     */
    /* ruleAttributeScope(scope)
     */
    ctx->poutput_templateParser_topStack->free(ctx->poutput_templateParser_topStack);



	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return output_templateParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_top176  */
static	ANTLR3_BITWORD FOLLOW_statement_in_top176_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000006FF0) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_top176	= { FOLLOW_statement_in_top176_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_top182  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_top182_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_top182	= { FOLLOW_EOF_in_top182_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditional_in_statement195  */
static	ANTLR3_BITWORD FOLLOW_conditional_in_statement195_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_conditional_in_statement195	= { FOLLOW_conditional_in_statement195_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_action_in_statement201  */
static	ANTLR3_BITWORD FOLLOW_action_in_statement201_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_action_in_statement201	= { FOLLOW_action_in_statement201_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attribute_in_statement207  */
static	ANTLR3_BITWORD FOLLOW_attribute_in_statement207_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attribute_in_statement207	= { FOLLOW_attribute_in_statement207_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_plaintext_in_statement213  */
static	ANTLR3_BITWORD FOLLOW_plaintext_in_statement213_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_plaintext_in_statement213	= { FOLLOW_plaintext_in_statement213_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LBR_in_conditional241  */
static	ANTLR3_BITWORD FOLLOW_LBR_in_conditional241_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000600) };
static  ANTLR3_BITSET_LIST FOLLOW_LBR_in_conditional241	= { FOLLOW_LBR_in_conditional241_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NOT1_in_conditional244  */
static	ANTLR3_BITWORD FOLLOW_NOT1_in_conditional244_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_NOT1_in_conditional244	= { FOLLOW_NOT1_in_conditional244_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAREN_in_conditional249  */
static	ANTLR3_BITWORD FOLLOW_LPAREN_in_conditional249_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAREN_in_conditional249	= { FOLLOW_LPAREN_in_conditional249_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_conditional253  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_conditional253_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_conditional253	= { FOLLOW_IDENT_in_conditional253_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_conditional255  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_conditional255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000006FF0) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_conditional255	= { FOLLOW_RPAREN_in_conditional255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_conditional269  */
static	ANTLR3_BITWORD FOLLOW_statement_in_conditional269_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000007FF0) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_conditional269	= { FOLLOW_statement_in_conditional269_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RBR_in_conditional275  */
static	ANTLR3_BITWORD FOLLOW_RBR_in_conditional275_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RBR_in_conditional275	= { FOLLOW_RBR_in_conditional275_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LBR_in_action303  */
static	ANTLR3_BITWORD FOLLOW_LBR_in_action303_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_LBR_in_action303	= { FOLLOW_LBR_in_action303_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AT_in_action305  */
static	ANTLR3_BITWORD FOLLOW_AT_in_action305_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_AT_in_action305	= { FOLLOW_AT_in_action305_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_action309  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_action309_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001200) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_action309	= { FOLLOW_IDENT_in_action309_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAREN_in_action324  */
static	ANTLR3_BITWORD FOLLOW_LPAREN_in_action324_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAREN_in_action324	= { FOLLOW_LPAREN_in_action324_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_action328  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_action328_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_action328	= { FOLLOW_IDENT_in_action328_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_action330  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_action330_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_action330	= { FOLLOW_RPAREN_in_action330_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RBR_in_action348  */
static	ANTLR3_BITWORD FOLLOW_RBR_in_action348_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RBR_in_action348	= { FOLLOW_RBR_in_action348_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LBR_in_attribute370  */
static	ANTLR3_BITWORD FOLLOW_LBR_in_attribute370_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_LBR_in_attribute370	= { FOLLOW_LBR_in_attribute370_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_attribute374  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_attribute374_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_attribute374	= { FOLLOW_IDENT_in_attribute374_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RBR_in_attribute376  */
static	ANTLR3_BITWORD FOLLOW_RBR_in_attribute376_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RBR_in_attribute376	= { FOLLOW_RBR_in_attribute376_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_esc_brackets_in_plaintext398  */
static	ANTLR3_BITWORD FOLLOW_esc_brackets_in_plaintext398_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_esc_brackets_in_plaintext398	= { FOLLOW_esc_brackets_in_plaintext398_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simple_text_in_plaintext403  */
static	ANTLR3_BITWORD FOLLOW_simple_text_in_plaintext403_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_simple_text_in_plaintext403	= { FOLLOW_simple_text_in_plaintext403_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ESC_LBR_in_esc_brackets419  */
static	ANTLR3_BITWORD FOLLOW_ESC_LBR_in_esc_brackets419_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ESC_LBR_in_esc_brackets419	= { FOLLOW_ESC_LBR_in_esc_brackets419_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ESC_RBR_in_esc_brackets437  */
static	ANTLR3_BITWORD FOLLOW_ESC_RBR_in_esc_brackets437_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ESC_RBR_in_esc_brackets437	= { FOLLOW_ESC_RBR_in_esc_brackets437_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_simple_text458  */
static	ANTLR3_BITWORD FOLLOW_set_in_simple_text458_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_simple_text458	= { FOLLOW_set_in_simple_text458_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start top
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:103:1: top : ( statement[true] )+ EOF ;
 */
static void
top(poutput_templateParser ctx)
{
    /* Initialize rule variables
     */
    ctx->poutput_templateParser_topTop = poutput_templateParser_topPush(ctx);

    	
    	
    	
    	//open files for reading
    	assert(GDATA!=NULL);
    	if(! GDATA->openFilesForReading())
      	{std::cout<<"\n Could not open files for reading";exit(1);}
      	
      	 
     	//open files for writing
     	((SCOPE_TOP(top))->h_file)=new std::ofstream;
    	((SCOPE_TOP(top))->cpp_file)=new std::ofstream;
    	
    	std::string fname;
     	fname=GDATA->getAttribute("OUTPUT_DIR")+"/"+GDATA->getAttribute("filename_h");
    	(SCOPE_TOP(top))->h_file->open(fname.c_str());
    	fname=GDATA->getAttribute("OUTPUT_DIR")+"/"+GDATA->getAttribute("filename_cpp");
    	(SCOPE_TOP(top))->cpp_file->open(fname.c_str());
    	
    	
    	//check if the files opened correctly
    	if(!(SCOPE_TOP(top))->h_file->is_open()) {std::cout<<"\nError opening file "<<fname;}
    	if(!(SCOPE_TOP(top))->cpp_file->is_open()) {std::cout<<"\nError opening file "<<fname;}
    	
    	
    	//start writing to the .h file by default
    	(SCOPE_TOP(top))->outfile=(SCOPE_TOP(top))->h_file;
    	//std::cout<<"\nWriting code into directory: "<<GDATA->getAttribute("output_dir");


    {
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:160:2: ( ( statement[true] )+ EOF )
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:160:4: ( statement[true] )+ EOF
        {
            // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:160:4: ( statement[true] )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	switch ( LA(1) )
            	{
            	case AT:
            	case ESC_LBR:
            	case ESC_RBR:
            	case IDENT:
            	case LBR:
            	case LPAREN:
            	case NOT1:
            	case PLAINTEXT:
            	case RPAREN:
            	case SLASH:
            		{
            			alt1=1;
            		}
            	    break;

            	}

            	switch (alt1)
            	{
            	    case 1:
            	        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:160:4: statement[true]
            	        {
            	            FOLLOWPUSH(FOLLOW_statement_in_top176);
            	            statement(ctx, true);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruletopEx;
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruletopEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

             MATCHT(EOF, &FOLLOW_EOF_in_top182);
            if  (HASEXCEPTION())
            {
                goto ruletopEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletopEx; /* Prevent compiler warnings */
    ruletopEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {

                    //close files
                    GDATA->closeFiles();
                    (SCOPE_TOP(top))->h_file->close();
                    (SCOPE_TOP(top))->cpp_file->close();

                }
            }


    poutput_templateParser_topPop(ctx);

    return ;
}
/* $ANTLR end top */

/**
 * $ANTLR start statement
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:164:1: statement[bool X] : ( conditional[X] | action[X] | attribute[X] | plaintext[X] );
 */
static void
statement(poutput_templateParser ctx, bool X)
{
    /* Initialize rule variables
     */

    {
        {
            //  /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:165:2: ( conditional[X] | action[X] | attribute[X] | plaintext[X] )

            ANTLR3_UINT32 alt2;

            alt2=4;

            switch ( LA(1) )
            {
            case LBR:
            	{
            		switch ( LA(2) )
            		{
            		case AT:
            			{
            				alt2=2;
            			}
            		    break;
            		case IDENT:
            			{
            				alt2=3;
            			}
            		    break;
            		case LPAREN:
            		case NOT1:
            			{
            				alt2=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 1;


            		    goto rulestatementEx;

            		}

            	}
                break;
            case AT:
            case ESC_LBR:
            case ESC_RBR:
            case IDENT:
            case LPAREN:
            case NOT1:
            case PLAINTEXT:
            case RPAREN:
            case SLASH:
            	{
            		alt2=4;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulestatementEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:165:4: conditional[X]
        	    {
        	        FOLLOWPUSH(FOLLOW_conditional_in_statement195);
        	        conditional(ctx, X);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:166:4: action[X]
        	    {
        	        FOLLOWPUSH(FOLLOW_action_in_statement201);
        	        action(ctx, X);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:167:4: attribute[X]
        	    {
        	        FOLLOWPUSH(FOLLOW_attribute_in_statement207);
        	        attribute(ctx, X);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;
        	case 4:
        	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:168:4: plaintext[X]
        	    {
        	        FOLLOWPUSH(FOLLOW_plaintext_in_statement213);
        	        plaintext(ctx, X);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end statement */

/**
 * $ANTLR start conditional
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:177:1: conditional[bool X] : ( LBR ( NOT1 )? LPAREN id= IDENT RPAREN ( statement[Xnext] )+ RBR ) ;
 */
static void
conditional(poutput_templateParser ctx, bool X)
{
    pANTLR3_COMMON_TOKEN    id;

    /* Initialize rule variables
     */


    bool Xnext=true;
    bool not_flag=false;

    id       = NULL;

    {
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:182:2: ( ( LBR ( NOT1 )? LPAREN id= IDENT RPAREN ( statement[Xnext] )+ RBR ) )
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:182:4: ( LBR ( NOT1 )? LPAREN id= IDENT RPAREN ( statement[Xnext] )+ RBR )
        {
            // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:182:4: ( LBR ( NOT1 )? LPAREN id= IDENT RPAREN ( statement[Xnext] )+ RBR )
            // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:182:5: LBR ( NOT1 )? LPAREN id= IDENT RPAREN ( statement[Xnext] )+ RBR
            {
                 MATCHT(LBR, &FOLLOW_LBR_in_conditional241);
                if  (HASEXCEPTION())
                {
                    goto ruleconditionalEx;
                }


                // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:182:9: ( NOT1 )?
                {
                    int alt3=2;
                    switch ( LA(1) )
                    {
                        case NOT1:
                        	{
                        		alt3=1;
                        	}
                            break;
                    }

                    switch (alt3)
                    {
                	case 1:
                	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:182:10: NOT1
                	    {
                	         MATCHT(NOT1, &FOLLOW_NOT1_in_conditional244);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleconditionalEx;
                	        }


                	        {
                	            not_flag=true;
                	        }


                	    }
                	    break;

                    }
                }

                 MATCHT(LPAREN, &FOLLOW_LPAREN_in_conditional249);
                if  (HASEXCEPTION())
                {
                    goto ruleconditionalEx;
                }


                id = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_conditional253);
                if  (HASEXCEPTION())
                {
                    goto ruleconditionalEx;
                }


                 MATCHT(RPAREN, &FOLLOW_RPAREN_in_conditional255);
                if  (HASEXCEPTION())
                {
                    goto ruleconditionalEx;
                }


                {

                    			if(X==false) Xnext=false;
                    				
                    			else
                    			{
                    			std::string s=(const char*)((id->getText(id))->chars);
                    			std::string cond=GDATA->getAttribute(s);
                    			if(cond=="") //attribute does not exist
                    				Xnext =false;
                    			 else Xnext=true;
                    			 
                    			if(not_flag==true) Xnext=!Xnext;
                    			}
                    		
                }


                // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:198:4: ( statement[Xnext] )+
                {
                    int cnt4=0;

                    for (;;)
                    {
                        int alt4=2;
                	switch ( LA(1) )
                	{
                	case AT:
                	case ESC_LBR:
                	case ESC_RBR:
                	case IDENT:
                	case LBR:
                	case LPAREN:
                	case NOT1:
                	case PLAINTEXT:
                	case RPAREN:
                	case SLASH:
                		{
                			alt4=1;
                		}
                	    break;

                	}

                	switch (alt4)
                	{
                	    case 1:
                	        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:198:5: statement[Xnext]
                	        {
                	            FOLLOWPUSH(FOLLOW_statement_in_conditional269);
                	            statement(ctx, Xnext);

                	            FOLLOWPOP();
                	            if  (HASEXCEPTION())
                	            {
                	                goto ruleconditionalEx;
                	            }


                	        }
                	        break;

                	    default:

                		if ( cnt4 >= 1 )
                		{
                		    goto loop4;
                		}
                		/* mismatchedSetEx()
                		 */
                		CONSTRUCTEX();
                		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
                		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


                		goto ruleconditionalEx;
                	}
                	cnt4++;
                    }
                    loop4: ;	/* Jump to here if this rule does not match */
                }

                 MATCHT(RBR, &FOLLOW_RBR_in_conditional275);
                if  (HASEXCEPTION())
                {
                    goto ruleconditionalEx;
                }


            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconditionalEx; /* Prevent compiler warnings */
    ruleconditionalEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end conditional */

/**
 * $ANTLR start action
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:208:1: action[bool X] : ( LBR AT id= IDENT ( LPAREN arg= IDENT RPAREN )? RBR ) ;
 */
static void
action(poutput_templateParser ctx, bool X)
{
    pANTLR3_COMMON_TOKEN    id;
    pANTLR3_COMMON_TOKEN    arg;

    /* Initialize rule variables
     */


    std::string s_id="";
    std::string s_arg="";

    id       = NULL;
    arg       = NULL;

    {
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:213:2: ( ( LBR AT id= IDENT ( LPAREN arg= IDENT RPAREN )? RBR ) )
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:213:4: ( LBR AT id= IDENT ( LPAREN arg= IDENT RPAREN )? RBR )
        {
            // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:213:4: ( LBR AT id= IDENT ( LPAREN arg= IDENT RPAREN )? RBR )
            // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:213:5: LBR AT id= IDENT ( LPAREN arg= IDENT RPAREN )? RBR
            {
                 MATCHT(LBR, &FOLLOW_LBR_in_action303);
                if  (HASEXCEPTION())
                {
                    goto ruleactionEx;
                }


                 MATCHT(AT, &FOLLOW_AT_in_action305);
                if  (HASEXCEPTION())
                {
                    goto ruleactionEx;
                }


                id = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_action309);
                if  (HASEXCEPTION())
                {
                    goto ruleactionEx;
                }


                {

                    			s_id=(const char*)((id->getText(id))->chars);
                    			
                }


                // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:217:3: ( LPAREN arg= IDENT RPAREN )?
                {
                    int alt5=2;
                    switch ( LA(1) )
                    {
                        case LPAREN:
                        	{
                        		alt5=1;
                        	}
                            break;
                    }

                    switch (alt5)
                    {
                	case 1:
                	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:218:3: LPAREN arg= IDENT RPAREN
                	    {
                	         MATCHT(LPAREN, &FOLLOW_LPAREN_in_action324);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleactionEx;
                	        }


                	        arg = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_action328);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleactionEx;
                	        }


                	         MATCHT(RPAREN, &FOLLOW_RPAREN_in_action330);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleactionEx;
                	        }


                	        {

                	            			s_arg=(const char*)((arg->getText(arg))->chars);
                	            			
                	        }


                	    }
                	    break;

                    }
                }

                 MATCHT(RBR, &FOLLOW_RBR_in_action348);
                if  (HASEXCEPTION())
                {
                    goto ruleactionEx;
                }


            }


            {

                		 if(X)
                		 {
                		 assert(OUTFILE.is_open());
                		
                		//take action
                		if(s_id=="add")
                		//dump contents of the specified file in outfile
                			{
                			if(s_arg=="includes") {OUTFILE<<I_file.rdbuf();}
                			else if(s_arg=="declarations") {OUTFILE<<D_file.rdbuf();}
                			else if(s_arg=="constructor") {OUTFILE<<C_file.rdbuf();}
                			else if(s_arg=="behavior") {OUTFILE<<E_file.rdbuf();}
                			else{std::cout<<"\nError in template for code generation:";
                			        std::cout<<" On line "<<(arg->getLine(arg))<<" unknown argument "<<s_arg;
                			        }
                			}
                		else if(s_id=="file")  //change destination file

                			{
                			if(s_arg=="h"||s_arg=="H") {(SCOPE_TOP(top))->outfile=(SCOPE_TOP(top))->h_file;}
                			else if(s_arg=="cpp"||s_arg=="CPP") {(SCOPE_TOP(top))->outfile=(SCOPE_TOP(top))->cpp_file;}
                			else{std::cout<<"\nError in template for code generation:";
                			        std::cout<<" On line "<<(arg->getLine(arg))<<" unknown argument "<<s_arg;
                			        }
                			}		
                		else
                			{
                			std::cout<<"\nError in template for code generation:";
                			std::cout<<" On line "<<(id->getLine(id))<<" unknown action "<<s_id;
                			        }
                		 }
                		 
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleactionEx; /* Prevent compiler warnings */
    ruleactionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end action */

/**
 * $ANTLR start attribute
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:262:1: attribute[bool X] : LBR id= IDENT RBR ;
 */
static void
attribute(poutput_templateParser ctx, bool X)
{
    pANTLR3_COMMON_TOKEN    id;

    /* Initialize rule variables
     */

    id       = NULL;

    {
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:263:2: ( LBR id= IDENT RBR )
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:263:4: LBR id= IDENT RBR
        {
             MATCHT(LBR, &FOLLOW_LBR_in_attribute370);
            if  (HASEXCEPTION())
            {
                goto ruleattributeEx;
            }


            id = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_attribute374);
            if  (HASEXCEPTION())
            {
                goto ruleattributeEx;
            }


             MATCHT(RBR, &FOLLOW_RBR_in_attribute376);
            if  (HASEXCEPTION())
            {
                goto ruleattributeEx;
            }


            {
                if(X)
                		{
                		 assert(OUTFILE.is_open());
                		 std::string s =(const char*)((id->getText(id))->chars);
                		 OUTFILE<<GDATA->getAttribute(s);
                		 }
                		 
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleattributeEx; /* Prevent compiler warnings */
    ruleattributeEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end attribute */

/**
 * $ANTLR start plaintext
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:275:1: plaintext[bool X] : ( esc_brackets[X] | simple_text[X] ) ;
 */
static void
plaintext(poutput_templateParser ctx, bool X)
{
    /* Initialize rule variables
     */

    {
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:276:2: ( ( esc_brackets[X] | simple_text[X] ) )
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:276:4: ( esc_brackets[X] | simple_text[X] )
        {
            // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:276:4: ( esc_brackets[X] | simple_text[X] )
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case ESC_LBR:
                case ESC_RBR:
                	{
                		alt6=1;
                	}
                    break;
                case AT:
                case IDENT:
                case LPAREN:
                case NOT1:
                case PLAINTEXT:
                case RPAREN:
                case SLASH:
                	{
                		alt6=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 6;
                    EXCEPTION->state        = 0;


                    goto ruleplaintextEx;

                }

                switch (alt6)
                {
            	case 1:
            	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:276:5: esc_brackets[X]
            	    {
            	        FOLLOWPUSH(FOLLOW_esc_brackets_in_plaintext398);
            	        esc_brackets(ctx, X);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleplaintextEx;
            	        }


            	    }
            	    break;
            	case 2:
            	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:276:23: simple_text[X]
            	    {
            	        FOLLOWPUSH(FOLLOW_simple_text_in_plaintext403);
            	        simple_text(ctx, X);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleplaintextEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleplaintextEx; /* Prevent compiler warnings */
    ruleplaintextEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end plaintext */

/**
 * $ANTLR start esc_brackets
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:281:1: esc_brackets[bool X] : ( ( ESC_LBR ) | ( ESC_RBR ) );
 */
static void
esc_brackets(poutput_templateParser ctx, bool X)
{
    /* Initialize rule variables
     */

    {
        {
            //  /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:282:2: ( ( ESC_LBR ) | ( ESC_RBR ) )

            ANTLR3_UINT32 alt7;

            alt7=2;

            switch ( LA(1) )
            {
            case ESC_LBR:
            	{
            		alt7=1;
            	}
                break;
            case ESC_RBR:
            	{
            		alt7=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleesc_bracketsEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:282:4: ( ESC_LBR )
        	    {
        	        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:282:4: ( ESC_LBR )
        	        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:282:5: ESC_LBR
        	        {
        	             MATCHT(ESC_LBR, &FOLLOW_ESC_LBR_in_esc_brackets419);
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleesc_bracketsEx;
        	            }


        	            {
        	                if(X)
        	                			{
        	                			assert(OUTFILE.is_open());
        	                			OUTFILE<<"<";
        	                			}
        	                			
        	            }


        	        }


        	    }
        	    break;
        	case 2:
        	    // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:291:3: ( ESC_RBR )
        	    {
        	        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:291:3: ( ESC_RBR )
        	        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:291:4: ESC_RBR
        	        {
        	             MATCHT(ESC_RBR, &FOLLOW_ESC_RBR_in_esc_brackets437);
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleesc_bracketsEx;
        	            }


        	            {
        	                if(X)
        	                			{
        	                			assert(OUTFILE.is_open());
        	                			OUTFILE<<">";
        	                			}
        	                			
        	            }


        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleesc_bracketsEx; /* Prevent compiler warnings */
    ruleesc_bracketsEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end esc_brackets */

/**
 * $ANTLR start simple_text
 * /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:301:1: simple_text[bool X] : ( IDENT | PLAINTEXT | SLASH | LPAREN | RPAREN | NOT1 | AT ) ;
 */
static output_templateParser_simple_text_return
simple_text(poutput_templateParser ctx, bool X)
{
    output_templateParser_simple_text_return retval;


    /* Initialize rule variables
     */

    retval.start = LT(1); retval.stop = retval.start;


    {
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:302:2: ( ( IDENT | PLAINTEXT | SLASH | LPAREN | RPAREN | NOT1 | AT ) )
        // /home/nehak/Desktop/sitarV2.0/translator/grammar/output_template.g:302:4: ( IDENT | PLAINTEXT | SLASH | LPAREN | RPAREN | NOT1 | AT )
        {
            if ( LA(1) == AT || LA(1) == IDENT || ((LA(1) >= LPAREN) && (LA(1) <= PLAINTEXT)) || ((LA(1) >= RPAREN) && (LA(1) <= SLASH)) )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto rulesimple_textEx;
            }


            {
                if(X)	
                		{
                		assert(OUTFILE.is_open());
                		OUTFILE<<STRSTREAM->toStringTT(STRSTREAM, retval.start, LT(-1))
                ->chars;
                		}
                		
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesimple_textEx; /* Prevent compiler warnings */
    rulesimple_textEx: ;
    retval.stop = LT(-1);


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return retval;
}
/* $ANTLR end simple_text */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
